### ISSUE TITLE
(py 3.6.3) Installation error: No pandoc was found

### ISSUE THREAD

**Issue by MarvBob** [Alir3z4/html2text#191]
I am making a python 3.6.3 virtual environment for testing.
When I try to install html2text I have an error with the following output:
```
(trois) C:\Sources\TEST>pip install html2text
Collecting html2text
  Using cached html2text-2017.10.4.tar.gz
    Complete output from command python setup.py egg_info:
    See http://johnmacfarlane.net/pandoc/installing.html
    for installation options
    ---------------------------------------------------------------

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\msv\AppData\Local\Temp\pip-build-6ofefsgv\html2text\setup.py", line 56, in <module>
        long_description=read_md('README.md'),
      File "C:\Users\msv\AppData\Local\Temp\pip-build-6ofefsgv\html2text\setup.py", line 8, in read_md_convert
        return convert(f, 'rst')
      File "c:\users\msv\envs\trois\lib\site-packages\pypandoc\__init__.py", line 69, in convert
        outputfile=outputfile, filters=filters)
      File "c:\users\msv\envs\trois\lib\site-packages\pypandoc\__init__.py", line 260, in _convert_input
        _ensure_pandoc_path()
      File "c:\users\msv\envs\trois\lib\site-packages\pypandoc\__init__.py", line 544, in _ensure_pandoc_path
        raise OSError("No pandoc was found: either install pandoc and add it\n"
    OSError: No pandoc was found: either install pandoc and add it
    to your PATH or or call pypandoc.download_pandoc(...) or
    install pypandoc wheels with included pandoc.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\msv\AppData\Local\Temp\pip-build-6ofefsgv\html2text\
```

Firstly, I would expect html2text to require pypandoc and install it as a dependency instead of raising an error, but the weird thing is that I already have pypandoc 1.4 installed in this environment.

**Comment by theSage21** [comment]
`pypandoc` is a wrapper around pandoc. I think you need pandoc separately installed. Pandoc is only included in the pre built package.

Can you confirm that this is the case? May be verify that pypandoc is usable otherwise in this environment with something like

```python
from pypandoc import convert
convert("hi", "rst")
```

**Comment by MarvBob** [comment]
Sorry for very late answer, but you were right, the test code you gave me failed so I installed pandoc and it works.
Thanks !
